Django_Practice/sales/urls.py
from django.urls import path, include

from .views import Homepage, SalesList, SalesDetail, SaleInput, SaleUpdate, SaleDelete
from .views import HomepageView, SalesInputView, SalesListView, SalesDetailView, SalesUpdateView, SalesDeleteView, SignupView

app_name = "Sales"

urlpatterns = [
    # path('', Homepage, name='Homepage'),  # 일반 함수 적용 형태
    path('', HomepageView.as_view(), name='Homepage'),  # 제너릭 뷰
    # path('sales', SalesList, name="List"),  # 일반 함수 적용 형태
    path('sales', SalesListView.as_view(), name="List"),  # 일반 함수 적용 형태
    # path('sales/<int:pk>', SalesDetail, name="Detail"), # 일반 함수 적용 형태
    path('sales/<int:pk>', SalesDetailView.as_view(), name="Detail"),  # 제너릭 뷰
    # path('sales/make', SaleInput, name="Create"), # 일반 함수 적용 형태
    path('sales/make', SalesInputView.as_view(), name="Create"),  # 제너릭 뷰
    # path('sales/<int:pk>/update', SaleUpdate, name="Update"), # 일반 함수 적용 형태
    path('sales/<int:pk>/update', SalesUpdateView.as_view(), name="Update"),  # 제너릭 뷰
    # path('sales/<int:pk>/delete', SaleDelete, name="Delete"), # 일반 함수 적용 형태
    path('sales/<int:pk>/delete', SalesDeleteView.as_view(), name="Delete"),  # 제너릭 뷰

    # 회원가입 url
    path('signup', SignupView.as_view(), name="Signup"),
]

Django_Practice/sales/models.py
from django.db import models

# 장고의 내장 유저 모델을 사용하고 싶은 경우 (간단한 방법)
# from django.contrib.auth import get_user_model
# ID = get_user_model()

# 장고에서 내장 유저 모델을 사용하는 기본적인 방법
# AbstractUser : 모델을 django에서 미리 지정해둬 간편하게 가져와 사용 가능
from django.contrib.auth.models import AbstractUser

from django.db.models.signals import post_save


class CustomID (AbstractUser):
    pass  # AbstractUser을 그대로 사용할 경우


class UserProfile(models.Model):
    customer = models.OneToOneField(CustomID, on_delete=models.CASCADE)

    def __str__(self):
        return self.customer.username


# 모델 생성 시 ID는 django에서 자동 생성!
class Sale(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField(default=0)
    person = models.ForeignKey("Person", on_delete=models.CASCADE)
    # models.SET_NULL : Null로 변경하고 싶은 경우
    # models.SET_DEFAULT : 삭제 시 기본값으로 지정하고 싶은 경우

    # funnels_type = (
    #     ('naver', '네이버'),
    #     ('google', '구글'),
    #     ('news', '뉴스레터'),
    # )

    # 다양한 타입 형태 존재
    # is_existed = models.BooleanField(default=False)
    # funnels = models.CharField(choices=funnels_type, max_length=200)
    # your_images = models.ImageField(blank=True, null=True)
    # your_file = models.FileField(blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Person(models.Model):
    customer = models.OneToOneField(CustomID, on_delete=models.CASCADE)
    groups = models.OneToOneField(
        UserProfile, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.customer.username


def CreateUserProfileSignal(sender, instance, created, **kwargs):
    # print(instance, created)  # 어떤 정보가 오는지 확인 (created : 새로 생성되는 경우만 True 반환)
    if created:
        UserProfile.objects.create(customer=instance)


post_save.connect(CreateUserProfileSignal, sender=CustomID)

Django_Practice/sales/forms.py
from django import forms
from .models import Sale

from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model

# 모델 폼


class SaleModelForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = (
            'first_name',
            'last_name',
            'age',
            'person'
        )


# 일반 폼
class SaleInputForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)


User = get_user_model()
# 회원가입 폼 (커스터마이징 UserCreationForm)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}

Django_Practice/sales/views.py
from django.views import generic
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse

from .models import CustomID, Sale, Person

from .forms import SaleInputForm, SaleModelForm, CustomUserCreationForm

from django.core.mail import send_mail

from django.contrib.auth.mixins import LoginRequiredMixin


def Homepage(request):
    # customer = CustomID.objects.all()
    # context = {
    #     "MenuName": "Noodle",
    #     "Price": "10,000 won",
    #     "Customer": customer
    # }
    # return render(request, "sales/index.html", context)
    return render(request, "sales/index.html")


def SalesList(request):
    sales = Sale.objects.all()

    sale_context = {
        "key": sales
    }

    return render(request, "sales/sales_list.html", sale_context)


def SalesDetail(request, pk):
    sale = Sale.objects.get(id=pk)
    detail_context = {
        "info": sale
    }
    # return HttpResponse(f"Detail Page - {sale.first_name} {sale.last_name}")
    return render(request, "sales/sales_detail.html", detail_context)


def SaleInput_1(request):
    # print(request.POST)   # 폼에 의해 입력 후 전송된 정보 확인

    # 유효성 확인되면 DB에 저장
    form = SaleInputForm()

    if request.method == "POST":
        form = SaleInputForm(request.POST)
        if form.is_valid():
            # print(form.cleaned_data)  # cleaned_data를 통해 필요한 정보들만 추려낼 수 있다
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            age = form.cleaned_data['age']
            person = Person.objects.first()

            Sale.objects.create(
                first_name=first_name,
                last_name=last_name,
                age=age,
                person=person
            )

            print("정보가 정상 입력되었습니다.")

            return redirect("/sales")

    context = {
        "form": form
    }

    return render(request, "sales/sales_input.html", context)


def SaleInput(request):
    # print(request.POST)   # 폼에 의해 입력 후 전송된 정보 확인

    # 유효성 확인되면 DB에 저장
    form = SaleModelForm()

    if request.method == "POST":
        form = SaleModelForm(request.POST)
        if form.is_valid():
            # print(form.cleaned_data)  # cleaned_data를 통해 필요한 정보들만 추려낼 수 있다

            # ModelForm을 쓰면 아래 절차를 생략할 수 있다
            form.save()

            # first_name = form.cleaned_data['first_name']
            # last_name = form.cleaned_data['last_name']
            # age = form.cleaned_data['age']
            # person = form.cleaned_data['person']

            # Sale.objects.create(
            #     first_name=first_name,
            #     last_name=last_name,
            #     age=age,
            #     person=person
            # )

            print("정보가 정상 입력되었습니다.")

            return redirect("/sales")

    context = {
        "form": form
    }

    return render(request, "sales/sales_input.html", context)


def SaleUpdate_1(request, pk):
    sales = Sale.objects.get(id=pk)
    form = SaleInputForm()

    if request.method == "POST":
        form = SaleInputForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            age = form.cleaned_data['age']
            person = Person.objects.first()

            sales.first_name = first_name
            sales.last_name = last_name
            sales.age = age
            sales.person = person

            sales.save()

            return redirect("/sales")

    context = {
        "sales": sales,
        "form": form,
    }

    return render(request, "sales/sales_update.html", context)


def SaleUpdate(request, pk):
    sales = Sale.objects.get(id=pk)

    # instance를 지정하여 pk가 일치하는 고객 정보를 form으로 지정하여 해당 값을 수정하도록 처리
    form = SaleModelForm(instance=sales)

    if request.method == "POST":
        form = SaleModelForm(request.POST, instance=sales)
        if form.is_valid():
            form.save()

            return redirect("/sales")

    context = {
        "sales": sales,
        "form": form,
    }

    return render(request, "sales/sales_update.html", context)


def SaleDelete(request, pk):
    sale = Sale.objects.get(id=pk)
    sale.delete()

    return redirect("/sales")


#################################################################
# 클래스를 이용한 뷰


class HomepageView(generic.TemplateView):
    template_name = "sales/index.html"


class SalesInputView(LoginRequiredMixin, generic.CreateView):
    template_name = 'sales/sales_input.html'
    form_class = SaleModelForm

    def get_success_url(self):
        return reverse("Sales:List")

    def form_valid(self, form):
        send_mail(
            subject="New Information Create",
            message="Go Homepage",
            from_email="admin@practice.com",  # 송신하는 자
            recipient_list=["test@test.com"]  # 수신하는 자
        )
        return super(SalesInputView, self).form_valid(form)

    # 기본적으로 Template에서 form으로 받도록 되어 있다 (다른 명칭 적용 X)


class SalesListView(LoginRequiredMixin, generic.ListView):
    template_name = "sales/sales_list.html"
    queryset = Sale.objects.all()
    context_object_name = "key"


class SalesDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "sales/sales_detail.html"
    queryset = Sale.objects.all()
    context_object_name = "info"


class SalesUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'sales/sales_update.html'
    queryset = Sale.objects.all()
    form_class = SaleModelForm
    context_object_name = "sales"

    def get_success_url(self):
        return reverse("Sales:List")


class SalesDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name = "sales/sales_delete.html"
    queryset = Sale.objects.all()

    def get_success_url(self):
        return reverse("Sales:List")


class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("Login")

Django_Practice/templates/sales/index.html
{% extends 'base.html' %} {% block content %}
<section class="text-gray-600 body-font">
  <div
    class="container mx-auto flex px-5 py-24 items-center justify-center flex-col"
  >
    <img
      class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded"
      alt="hero"
      src="https://dummyimage.com/720x600"
    />
    <div class="text-center lg:w-2/3 w-full">
      <h1
        class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900"
      >
        Django Sales Management - Django Refresh
      </h1>
      <p class="mb-8 leading-relaxed">Django 복습</p>
      <div class="flex justify-center">
        <button
          class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
        >
          Button
        </button>
        <button
          class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg"
        >
          Button
        </button>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

Django_Practice/templates/sales/sales_delete.html
{% extends "base.html" %} {% block content %}
<p>정말 삭제하시겠습니까?</p>
<form method="post">
  {% csrf_token %}
  <button
    type="submit"
    class="text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"
  >
    삭제하기
  </button>
</form>
{% endblock content %}

Django_Practice/templates/sales/sales_detail.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">상세 목록</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{info.last_name}} {{info.first_name}}</h1>
        <div class="flex mb-4">
          <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">고객 정보</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">평가</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">상세정보</a>
        </div>
        <p class="leading-relaxed mb-4">{{info.last_name}} {{info.first_name}} 님의 고객 정보입니다.</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">나이</span>
          <span class="ml-auto text-gray-900">{{info.age}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">지역</span>
          <span class="ml-auto text-gray-900">미공개</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">담당자</span>
          <span class="ml-auto text-gray-900">{{info.person}}</span>
        </div>
        <div class="flex">
          <a class="flex ml-auto" href={% url "Sales:Update" info.pk %}><button class="text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">업데이트</button></a>
          <a href={% url "Sales:Delete" info.pk %}><button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
            </svg>
          </button></a>
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>

{% comment %}
<h1>상세 목록 - {{info.last_name}} {{info.first_name}}</h1>
<p>나이 : {{info.age}}</p>
<p>담당자 명 : {{info.person}}</p>

<a href={% url "Sales:Update" info.pk %}>업데이트</a>
<a href={% url "Sales:Delete" info.pk %}>삭제</a> {% endcomment %}
{% endblock content %}

Django_Practice/templates/sales/sales_input.html
{% extends 'base.html' %} {% block content %}
<p>정보을 입력해주세요</p>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">추가</button>
</form>
{% endblock content %}

Django_Practice/templates/sales/sales_list.html
{% extends "base.html" %}

{% block content %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
  <div class="w-full">
    <div><h1 class="text-blue-800">세일 목록</h1></div>
    <div class="w-full">
    <div class="mb-5 text-yellow-800"><a href={% url 'Sales:Create' %}>신규생성</a></div>
    </div>
  </div>
    {% for sale in key %}
    <div class="flex flex-wrap -m-4">
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{sale.last_name}} {{sale.first_name}}</h2>
            <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
            <a href={% url 'Sales:Detail' sale.pk %} class="mt-3 text-indigo-500 inline-flex items-center">Learn More
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</section>



  {% comment %} {% for sale in key %}
  <div class="sales">
    <a href={% url 'Sales:Detail' sale.pk %}
      >{{ sale.first_name }} {{sale.last_name}} &nbsp (Age : {{ sale.age}})</a
    >
    <br />
  </div>
  {% endfor %} {% endcomment %}
{% endblock content %}

Django_Practice/templates/sales/sales_update.html
{% extends 'base.html' %}


{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">상세 목록</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{sales.last_name}} {{sales.first_name}}</h1>
        <div class="flex mb-4">
          <a class="flex-grow text-red-500 border-b-2 border-red-500 py-2 text-lg px-1">고객 정보</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">평가</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">상세정보</a>
        </div>
        <p class="leading-relaxed mb-4">{{sales.last_name}} {{sales.first_name}} 님의 수정 가능한 고객 정보입니다.</p>
        <form method="post">
          {% csrf_token %} {{ form.as_p }}
          <div class="flex mt-10">
          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" type='submit'>업데이트</button>
          <a href={% url "Sales:Detail" sales.pk %} class="inline-flex items-center justify-center text-white bg-gray-500 border-0 py-2 px-6 focus:outline-none hover:bg-gray-600 rounded ml-4"> 돌아가기 </a>
          </div>
        </form>
        </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>


{% endblock content %}