Django_TEST/API_TEST/API_TEST/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include("users.urls")),
]

Django_TEST/API_TEST/users/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("signup", views.signup_view, name="signup")
]

Django_TEST/API_TEST/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser) :
    pwd_id = models.CharField(max_length=100)

Django_TEST/API_TEST/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, JsonResponse
from .models import User

# Create your views here.
def login_view(request) :
    if request.method == "POST" :
        # print(request.POST)
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None :
            print("로그인 성공")
            login(request, user)
            # return HttpResponse(status=200)
        else :
            print("로그인 실패")
            # return HttpResponse(status=401)
    return render(request, "users/login.html")

def logout_view(request) :
    logout(request)
    return redirect("user:login")

def signup_view(request) :
    
    if request.method == "POST" :
        print(request.POST)
        username = request.POST["username"]
        password = request.POST["password"]
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        email = request.POST["email"]
        pwd_id = request.POST["pwd_id"]
        
        user = User.objects.create_user(username, email, password)
        user.first_name = first_name
        user.last_name = last_name
        user.pwd_id = pwd_id
        user.save()
        return redirect("user:login")
    return render(request, "users/signup.html")

Django_TEST/API_TEST/users/templates/users/login.html
<h1>로그인 페이지</h1>
<br />

{% if user.is_authenticated %}
<!-- 로그인 성공 시 -->
로그인 성공! {{user.username}}님 환영합니다.
<!-- 로그인 성공 -->
<a href="{% url 'user:logout' %}">로그아웃</a>
{% else %}
<!-- 로그인 실패 시 로그인 페이지로 되돌아가기 -->

<form action="" method="POST">
  {% csrf_token %}
  <input name="username" type="text" />
  <input name="password" type="password" />
  <input type="submit" value="로그인" />
</form>
<a href="{% url 'user:signup' %}">회원가입</a>
<!-- 로그인 페이지 반환 -->
{% endif %}

Django_TEST/API_TEST/users/templates/users/signup.html
<h1>회원가입 페이지</h1>
<br />

<form action="" method="POST">
  {% csrf_token %}
  <p>아이디</p>
  <input name="username" type="text" />
  <p>비밀번호</p>
  <input name="password" type="password" />
  <p>성</p>
  <input name="last_name" type="text" />
  <p>이름</p>
  <input name="first_name" type="text" />
  <p>이메일</p>
  <input name="email" type="text" />
  <p>발전소번호</p>
  <input name="pwd_id" type="text" />
  <br />
  <br />
  <input type="submit" value="회원가입" />
</form>