Django_Practice/sales/urls.py
from django.urls import path, include

from .views import Homepage, SalesList, SalesDetail, SaleInput, SaleUpdate, SaleDelete
from .views import HomepageView, SalesInputView, SalesListView, SalesDetailView, SalesUpdateView, SalesDeleteView, SignupView

app_name = "Sales"

urlpatterns = [
    # path('', Homepage, name='Homepage'),  # 일반 함수 적용 형태
    path('', HomepageView.as_view(), name='Homepage'),  # 제너릭 뷰
    # path('sales', SalesList, name="List"),  # 일반 함수 적용 형태
    path('sales', SalesListView.as_view(), name="List"),  # 일반 함수 적용 형태
    # path('sales/<int:pk>', SalesDetail, name="Detail"), # 일반 함수 적용 형태
    path('sales/<int:pk>', SalesDetailView.as_view(), name="Detail"),  # 제너릭 뷰
    # path('sales/make', SaleInput, name="Create"), # 일반 함수 적용 형태
    path('sales/make', SalesInputView.as_view(), name="Create"),  # 제너릭 뷰
    # path('sales/<int:pk>/update', SaleUpdate, name="Update"), # 일반 함수 적용 형태
    path('sales/<int:pk>/update', SalesUpdateView.as_view(), name="Update"),  # 제너릭 뷰
    # path('sales/<int:pk>/delete', SaleDelete, name="Delete"), # 일반 함수 적용 형태
    path('sales/<int:pk>/delete', SalesDeleteView.as_view(), name="Delete"),  # 제너릭 뷰

    # 회원가입 url
    path('signup', SignupView.as_view(), name="Signup"),
]

Django_Practice/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Django Refresh</title>
    <link href={% static 'css/style.css'%}/>

    {% comment %} 부트스트랩 CDN {% endcomment %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    {% comment %} 테일윈드 CDN {% endcomment %}
    <script src="https://cdn.tailwindcss.com"></script>
    {% comment %}
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp,container-queries"></script>
    {% endcomment %} {% comment %}
    <script>
      tailwind.config = {
        theme: {
          extend: {
            colors: {},
          },
        },
      };
    </script>
    {% endcomment %} {% comment %}
    <style>
      .sales {
        padding-top: 20px;
        padding-bottom: 30px;
        padding-right: 10px;
        padding-left: 10px;
        background-color: #cdcdcd;
      }
    </style>
    {% endcomment %}
  </head>
  <body>
    {% comment %} <div class="max-w-7xl mx-auto bg-gray-600 bg-opacity-60"> {% endcomment %}
    <div class="max-w-7xl mx-auto bg-white-600 bg-opacity-60">
      {% include 'menu.html' %} {% block content %} {% endblock content %}
    </div>
    {% include 'parts.html' %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

Django_Practice/templates/menu.html
<header class="text-gray-600 body-font">
  <div
    class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center"
  >
    <a
      class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full"
        viewBox="0 0 24 24"
      >
        <path
          d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"
        ></path>
      </svg>
      <a href={% url "Sales:Homepage" %}><span class="ml-3 text-xl">Sales Management</span></a>
    </a>
    <nav
      class="md:ml-auto flex flex-wrap items-center text-base justify-center"
    >
      <a href={% url "Sales:List" %} class="mr-5 hover:text-gray-900">List</a>
      {% if not request.user.is_authenticated %}
        <a href={% url "Sales:Signup" %} class="mr-5 hover:text-gray-900">Sign Up</a>
      {% endif %}
    </nav>
    {% if request.user.is_authenticated %}
      {{request.user.username}} 님
      <form action="{% url 'Logout' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Logout" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0" />
    </form>
    {% else %}
    <a
      href={% url "Login" %}
      class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0"
    >
      Login
      <svg
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        class="w-4 h-4 ml-1"
        viewBox="0 0 24 24"
      >
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>
    {% endif %}
  </div>
</header>

Django_Practice/templates/parts.html
{% load static %}

<script src={% static 'js/main.js' %}></script>